### ISSUE TITLE
Any idea why the weather forecasts are for previous days not upcoming days?

### ISSUE THREAD

**Issue by omiq** [null8626/python-weather#12]
<img width="442" alt="Screen Shot 2021-07-14 at 11 59 50 AM" src="https://user-images.githubusercontent.com/3143825/125670287-15171456-e01d-422c-9b7b-3dd91486ce03.png">

**Comment by vierofernando** [comment]
strange, can you tell me on what version of the library you are using and steps on how to reproduce the bug?

**Comment by omiq** [comment]
I installed using pip so presumably the latest version?

My guess is something around caching because changing from Imperial to Metric doesn't seem to change the results?

<img width="1025" alt="Screen Shot 2021-07-16 at 10 12 52 AM" src="https://user-images.githubusercontent.com/3143825/125977638-1977ce40-2afb-42b7-b184-b8aa12332b20.png">

**Comment by vierofernando** [comment]
i'm sorry, but i think this could be an issue with the timezone, or the rest API itself. i tried it in my machine and it worked just fine.

**Comment by daniellukeahead** [comment]
I encountered the same issue. If it is about the timezone, it will not be several days difference.

**Comment by ClimberMel** [comment]
Is this still a problem?  It works on my system (West Coast Canada).  It does give me the previous day, but I really like that, since it is really having what the forecast was for the current day.

**Comment by null8626** [comment]
Issue closed - as it's stale
