### ISSUE TITLE
when passing in to the function different locations nothing returns.

### ISSUE THREAD

**Issue by kroboo** [null8626/python-weather#22]
i ve been trying to make a weather function for my discord application using python weather but every time i pass a different city other than : "Bucharest" or "Washington DC" . The following comes up.
![image](https://user-images.githubusercontent.com/93818842/179624983-2e5fb38a-6e3d-47f6-b1d5-ac54d181483b.png)
i ve tried looking up the errors and nothing seems to work really. i dont know if this is an actual bug or me just being dump.
for reference this is the script i wrote:
```py
import python_weather
import asyncio
class WeatherFunc:
    def __init__(self,location):
        self.client = python_weather.Client(format=python_weather.METRIC)
        self.location = location


    async def on_call(self):
        weather = await self.client.find(self.location)
        print(weather.current.temperature)



        await self.client.close()
object1  = WeatherFunc("Sofia")
if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(object1.on_call())
```
if by any chance i am wrong sorry for addressing my issue and please tell me what i should change.

- [ ] 

- [ ] #22

**Comment by kroboo** [comment]
@null8626

**Comment by null8626** [comment]
I'll look into it in a while! Thanks for the report.

**Comment by kroboo** [comment]
@null8626 Thank you as well for responding ! notify me when you resolve the bug.All the best regards!

**Comment by null8626** [comment]
<3

**Comment by null8626** [comment]
This issue seems to be related to #25. Closing, sorry!
