### ISSUE TITLE
The MSN API is retired

### ISSUE THREAD

**Issue by danyx23** [null8626/python-weather#25]
Hi! Thanks for this library! I use it to figure out how often my watering system should turn on depending on the temperature forecast. This worked super well but now I noticed that it seemed to water them too often. When investigating, I found that running the code sample below I always get 2022-06-24 as the current date. Has something changed with the API that is used under the hood?

```python
import python_weather
import asyncio
client = python_weather.Client()
weather = await client.find("Berlin, Germany")
weather.current.date
# datetime.datetime(2022, 6, 24, 18, 0)
```

**Comment by danyx23** [comment]
It looks like MSN retired their API: https://docs.microsoft.com/en-us/sharepoint/troubleshoot/apps/msn-weather-service-api-retired

**Comment by null8626** [comment]
Huh, i'll make this library switch to use another API. `wttr.in` seems like a good third-party replacement.

**Comment by null8626** [comment]
A work is in progress, be patient! <3

**Comment by danyx23** [comment]
Thank you! I've switched to using raw wttr.in for now for watering my plants but great if you can make this library work again with wttr.in as a backend.

**Comment by null8626** [comment]
[It's here!](https://github.com/null8626/python-weather/releases/tag/0.4.0)
