### ISSUE TITLE
print(forecast) returns AttributeError

### ISSUE THREAD

**Issue by Pigeon43** [null8626/python-weather#30]
`for forecast in weather.forecasts:
print(forecast)`
returns the following error:
`AttributeError: 'DailyForecast' object has no attribute 'temperature'`

**Comment by null8626** [comment]
Will look into this in a while, thanks for the report!

**Comment by null8626** [comment]
Sorry for the long delay, but this bug is now fixed in [this commit!](https://github.com/null8626/python-weather/commit/3792a0e1cb29fde97a074621478ffb1f9093d09a)
