### ISSUE TITLE
Temperature is incorrect and with/without state produces different results

### ISSUE THREAD

**Issue by jkc120** [null8626/python-weather#31]
I'm getting wildly inaccurate temperatures and I cannot pinpoint why. I thought it was because the city was obscure/smaller, but even for some larger cities, it's way off. 

Here's some sample code:

```
import python_weather
import asyncio
import os
import sys
import re
from uszipcode import SearchEngine

async def getweather(place):
  async with python_weather.Client(format=python_weather.IMPERIAL) as client:

    weather = await client.get(place)
    print(weather.current.temperature)
    print(weather.current.description)

if __name__ == "__main__":
    city = sys.argv[1]
    place = city

    if re.match(r'^\d{5}', city):
        engine = SearchEngine()
        zipcode = engine.by_zipcode(city)
        city = zipcode.major_city
        state = zipcode.state
        place = f"{city}, {state}"

    asyncio.run(getweather(place))
```

Output for "Folsom, CA":

% ./w.py "Folsom, CA"
75
Sunny

weather.com reports sunny and 82 and accuweather 85, so 75 seems way off. Even for Atlanta, GA it's off:

% ./w.py "Atlanta, GA"
74
Partly cloudy

weather.com reports partly cloudy and 78, and accuweather 79.

Note that I'm not even using the zip code lookup. I've also tried without the state with different (but also inaccuate) results:

% ./w.py Atlanta
71
Partly cloudy

Here's the version I'm using with Python 3.9:

% /usr/bin/python3.9 -c 'import python_weather; print(python_weather.__version__)'
0.4.1

Thanks,
Josh

**Comment by null8626** [comment]
Today i tried looking up `Atlanta, GA` on `weather.com` and it yielded the temperature as 76 degrees.

After comparing it with `wttr.in`'s results:
- query `Atlanta` yields 75 degrees
- query `Atlanta, GA` yields 71 degrees

So, this could be either an issue with the API being inaccurate, or the fact that the API doesn't handle requests in a `{city}, {state}` format well.

**Comment by wizpig64** [comment]
For what it's worth, `wttr.in`'s data for my region seems to be about 10 degrees off from what google (citing `weather.com`) shows me, too.

**Comment by jkc120** [comment]
> 

Things seem off even by zip code. Example for Folsom, CA's zip:

% ./w.py 95630
84
Haze

Google's weather result reports 89 and sunny.

And for Richmond, CA, Google's weather reports 71 and mostly sunny as compared to:

% ./w.py 94805
83
Sunny

**Comment by null8626** [comment]
> Things seem off even by zip code. Example for Folsom, CA's zip:
> 
> % ./w.py 95630 84 Haze
> 
> Google's weather result reports 89 and sunny.
> 
> And for Richmond, CA, Google's weather reports 71 and mostly sunny as compared to:
> 
> % ./w.py 94805 83 Sunny

the reason could be what i've said earlier

**Comment by null8626** [comment]
Sounds like it!
