### ISSUE TITLE
How to convert time to normal view ?

### ISSUE THREAD

**Issue by Kalinka5** [null8626/python-weather#33]
When I use:

for forecast in weather.forecasts:
    for hourly in forecast.hourly:
        resp_msg += f'Time: {hourly.time}\n'\
                    f'Temperature: {round((hourly.temperature - 32) / 1.8)}°C\n'\
                    f'Description: {hourly.description}\n'\
                    f'Type: {hourly.type}\n\n'

My bot returns: 

Time: 0
Temperature: 17°C
Description: Partly cloudy
Type: Partly Cloudy

Time: 300
Temperature: 17°C
Description: Partly cloudy
Type: Partly Cloudy

Time: 600
Temperature: 16°C
Description: Partly cloudy
Type: Partly Cloudy

Time: 900
Temperature: 19°C
Description: Patchy rain possible
Type: Light Showers

How can I transform "Time" from 600 to 6:00?

**Comment by null8626** [comment]
this looks like a genuine misinterpretation of the API's response on my end, i should've turned this to a python `time` object instead of a raw `int`. i'll change this in a future update, thanks!

**Comment by null8626** [comment]
Fixed in version [`0.4.3`](https://github.com/null8626/python-weather/releases/tag/0.4.3).
