### ISSUE TITLE
City list

### ISSUE THREAD

**Issue by nmfernandes70** [null8626/python-weather#34]
Hi
How can one know the city names available ? ( i.e Portuguese cities: Lisbon or Lisboa seems not to be available, Funchal is available).

Thks!
Nuno

**Comment by null8626** [comment]
feel free to ask about this in the official repository of the API: https://github.com/chubin/wttr.in/issues

**Comment by nmfernandes70** [comment]
Have looked at the official repository of the API that you mentioned and found out that works fine using airport codes (i.e LIS for Lisbon). Thanks for the info.

**Comment by null8626** [comment]
no problem! glad to help <3
