### ISSUE TITLE
Problem with forecasts

### ISSUE THREAD

**Issue by Kalinka5** [null8626/python-weather#35]
I make the weather bot in telegram. There are 5 buttons, 2 are forecasts (Hourly_forecasts and Daily_forecasts). When I click one of 2 buttons It displays what I need, but when I click another forecasts It return error.
Photo of clicking forecasts button:

![photo_5271836120210065227_y](https://user-images.githubusercontent.com/106172806/209168261-3b41cad2-da7d-4ee1-87f6-03a31288aee4.jpg)
![photo_5271836120210065230_y](https://user-images.githubusercontent.com/106172806/209169247-f28018a2-3f3b-4dcd-b277-9ac6e0df3b7d.jpg)
![photo_5271836120210065232_y](https://user-images.githubusercontent.com/106172806/209169309-90507866-b773-4410-b691-3230d2f1f967.jpg)

Errors:

![изображение_2022-12-22_172030819](https://user-images.githubusercontent.com/106172806/209165982-082830f3-228e-4efc-9e29-0076ed5c1cd8.png)
![изображение_2022-12-22_173833556](https://user-images.githubusercontent.com/106172806/209169524-33183a04-5cf7-44e6-ae95-faa3f9e3e929.png)

And 3 rest buttons click as much as I want:

![photo_5271836120210065225_y](https://user-images.githubusercontent.com/106172806/209170074-c534ca86-693a-493b-8d5b-8949f7e30786.jpg)
![photo_5271836120210065226_y](https://user-images.githubusercontent.com/106172806/209170191-571d6578-cd70-4c59-8c82-7a22c6035536.jpg)
 
Is that API problem or Bot problem ?

**Comment by null8626** [comment]
looks like a bug to me, will fix soon! thanks for the report <3

**Comment by null8626** [comment]
hmmmm, i don't seem to find a way to properly find the source of the issue, this could be a problem with the API itself

**Comment by null8626** [comment]
for now, i think the choice i would recommend is making an error handler for it. since i don't think can find a way to fix the issue (in the library level), sorry about that!

**Comment by null8626** [comment]
i could create an update that creates an error handler for this that ignores malformed API responses, but it might have the possibility to return empty values, which could be confusing to the users using this library.

**Comment by Kalinka5** [comment]
Hmmmm, Okay. I'll try to work around this issue for now. I hope, you will find the source of the issue soon.

**Comment by xcloudyunx** [comment]
I came across the same issue and have a fix for it. However, I don't seem to be able to create a branch for a PR. Do I push to main straight away?

**Comment by null8626** [comment]
Fixed in #41.
