### ISSUE TITLE
Sky_text aint working

### ISSUE THREAD

**Issue by Kenimusic** [null8626/python-weather#36]
![image](https://user-images.githubusercontent.com/45991429/209581341-04b5aed3-2259-4dbe-82db-7d88e1e2f2e2.png)
I don't really get the reason because of which the "sky_text" aint working .

P.S i am very new to programming and codding.

**Comment by null8626** [comment]
can you show me the error causing this?

**Comment by null8626** [comment]
the field `sky_text` is already removed in the recent update, please update to the most recent version! with `pip install -U python_weather` and use the most recent example in [examples.py](https://github.com/null8626/python-weather/blob/main/example.py)!
