### ISSUE TITLE
How can i show where the weather is shown?

### ISSUE THREAD

**Issue by Mx121** [null8626/python-weather#37]

**Comment by null8626** [comment]
I'm sorry, but may you elaborate on your question?

**Comment by Mx121** [comment]
How can I show a city?

**Comment by null8626** [comment]
Hi! sorry for the long response,

i'm sure you can retrieve the location of the forecast by doing `<Weather>.nearest_area`. This `NearestArea` object should let you retrieve other things too like the location name (`<Weather>.nearest_area.name`), region name (`<Weather>.nearest_area.region`), or country name (`<Weather>.nearest_area.country`).

Hope this helps!
