### ISSUE TITLE
Set days in forecast

### ISSUE THREAD

**Issue by Andymator21** [null8626/python-weather#38]
Hello
Thank you for your great work! Im a highsctool teacher that will teach my students to use this project on their RPis.
I have a question. Is it possible to get more days than three in the forecast?
And I am sorry if this is not actually an issue, but I did not know any other way to reach you.
Regards, David in Sweden

**Comment by null8626** [comment]
Hi! I'm genuinely so honored for my library to be used a teaching tool for your highschool students - Thanks!

I'm sorry, but i'm afraid the Web API we're depending on to make this library - [`wttr.in`](https://wttr.in) only returns three weather forecasts... so i'm afraid it's not possible... sorry if this is a bummer to you.
