### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by owfran** [null8626/python-weather#47]
Hi, I am pretty new to coding and wanted to use this for a project. I am using a raspberry pi4. I have downloaded the source distribution from pypi.org and extracted them to my downloads, but when I run  $ pip install python-weather  I get an error like this:
IOError: [Errno 2] No such file or directory: '/tmp/pip-build-( )/python-weather/setup.py'    where inside of the ( ) is a random 6 letter/number code that changes every time I run it.
Any help would be appreciated.

**Comment by null8626** [comment]
Hello! I suppose your `pip` are not up-to-date according to [this stackoverflow thread](https://stackoverflow.com/questions/51405580/pip-install-filenotfounderror-errno-2-no-such-file-or-directory). Have you tried updating them with `pip install --upgrade pip`? Thanks!

**Comment by owfran** [comment]
Sorry for the late reply. Yes, this worked thanks a bunch!

**Comment by null8626** [comment]
No problem! glad to have helped! ❤️❤️❤️
