### ISSUE TITLE
Unable to install for Python 3.12; aiohttp needs upgrading to 3.9.0?

### ISSUE THREAD

**Issue by oaustegard** [null8626/python-weather#50]
When attempting to install python-weather 1.0.3 there are a handful of issues

* It seems to use aiohttp==3.8.4 despite 3.8.6 being listed in the https://github.com/null8626/python-weather/blob/main/pyproject.toml file
* aiohttp 3.8.4 wheel build fails, as does a `pip install aiohttp==3.8.6`
* `pip install aiohttp --no-cache-dir` installs v 3.9.0 (released 5 days ago) *works*

**Comment by oaustegard** [comment]
Ah, yes directly related to https://github.com/null8626/python-weather/pull/49 I see

**Comment by oaustegard** [comment]
PS! Thanks!

**Comment by null8626** [comment]
Hai! This issue was fixed under [`v1.1.0`](https://github.com/null8626/python-weather/releases/tag/1.1.0).
