### ISSUE TITLE
What is "rem dry"?

### ISSUE THREAD

**Issue by joshinils** [null8626/python-weather#53]
English is not my native language, googling was not really helpful.

**Comment by null8626** [comment]
`rem dry` stands for `Remaining dry`. It's represented in percentages in this library, thus `chanceofremdry` returns the chance of remaining dry in percentage.

**Comment by joshinils** [comment]
So it means the chance of no rain (at all) but not stated as a negative?

**Comment by null8626** [comment]
Sounds like it. I might update this library to address further confusion in the future.
