### ISSUE TITLE
The unit of precipitation is wrong in documentation.

### ISSUE THREAD

**Issue by VijaySamant4368** [null8626/python-weather#58]
Hello, this is just my thought, but I think that the unit of precipitation in the documentation is not correct.
To quote the [documentation](https://python-weather.readthedocs.io/en/latest/forecast/weather.html#python_weather.forecast.Forecast.precipitation),
```
The precipitation in either Millimeters or Inches.
```
But I noticed two things:
- The value of `python_weather.forecast.Forecast.precipitation` is, as far as I checked, always between 0.0 and 1.0 .
- Even when I change the units from METRIC to IMPERIAL, the value of `python_weather.forecast.Forecast.precipitation` is remaining the same.
Noticing these two things I concluded that the value is actually "Probability of Precipitation", none other alternatives feels correct to me.
If I may suggest, the documentation can be updated to:
```
The "Probability of Precipitation" value.
```

**Comment by null8626** [comment]
Hai! Thank you so much for reporting this.

**Comment by null8626** [comment]
Hi again. After looking at [the API's source code for `precipitation`](https://github.com/chubin/wttr.in/blob/575908ae51010b2d71c0b1d4bf4def997bea0fa3/lib/metno.py#L311-L345), it seems that the library's documentation is correct, though? I've tried testing the library by fetching weather forecasts for some locations and sometimes `precipitation` would be greater than `1.0` (e.g `1.7`).

**Comment by VijaySamant4368** [comment]
Oh it seems I looked at little sample of examples. But there still is the problem that even when the units change, the value remains same, while for different properties like `python_weather.forecast.Forecast.temperature` do change.

**Comment by null8626** [comment]
It seems that the value is different for different units though? I understand that it's the same when both values are zero but [the source code for the API denies this](https://github.com/chubin/wttr.in/blob/575908ae51010b2d71c0b1d4bf4def997bea0fa3/lib/metno.py#L344-L345).

**Comment by VijaySamant4368** [comment]
I am sorry, the bug was in my implementation of code. It was really hard to find, sorry for wasting your time.

**Comment by null8626** [comment]
All good!
