### ISSUE TITLE
Quesion: Do we have a limit calling the API?

### ISSUE THREAD

**Issue by junekhan** [null8626/python-weather#61]
Thank you for the great job! I'm particularly concerned about how many times we can call daily?

**Comment by null8626** [comment]
Hai. Sorry for the late response -- I was really busy with uni!

While undocumented, after looking at [wttr.in's source code](https://github.com/chubin/wttr.in/), it seems that the API by default imposes rate limits of 300 requests/minute, 3,600 requests/hour, and 86,400 requests/day. (See [the `QUERY_LIMITS` constant in `globals.py`](https://github.com/chubin/wttr.in/blob/355a515b1f9ea31b193cb9c1d3cef5e5dff07de9/lib/globals.py#L64-L66) and [the `Limits` class in `limits.py`](https://github.com/chubin/wttr.in/blob/355a515b1f9ea31b193cb9c1d3cef5e5dff07de9/lib/limits.py#L31)).

Feel free to correct me if I was wrong. Thanks!

**Comment by junekhan** [comment]
@null8626 Thanks for looking up the limits!
